### ISSUE TITLE
Unable to use OutOfRange<T> with decimal types

### ISSUE THREAD

**Issue by fingers10** [ardalis/GuardClauses#46]
Dear Steve,

I'm not able to use `OutOfRange` for decimal types like `Guard.Against.OutOfRange(unitPrice, nameof(unitPrice), 0, decimal.MaxValue);` when I checked the source code, I can [see](https://github.com/ardalis/GuardClauses/blob/master/src/GuardClauses/GuardClauseExtensions.cs#L132) that `OutOfRange` is marked `private`. Please can you change that to `public`? This could help to use it with many types. Correct me if I'm wrong.

Thanks,
Abdul

**Comment by KyleMcMaster** [comment]
Hello!
Rather than marking the `OutOfRange` method cited above as public, would it be better to implement another extension method specifically for the `Decimal` type?

Something like:
`public static void OutOfRange(this IGuardClause guardClause, Decimal input, string parameterName, Decimal rangeFrom, Decimal rangeTo)`

I can put in a PR for the above if needed. :)

**Comment by fingers10** [comment]
@KyleMcMaster  what if you need for some other type in future? Instead of keep adding new extension making it public would help right?

**Comment by KyleMcMaster** [comment]
@fingers10 It appears `OutOfRange` has been kept private for a reason, as a public implementation of it for int, datetime, and enum types already exists.

**Comment by fingers10** [comment]
again what about `short` or any other types?

**Comment by ardalis** [comment]
The current pattern followed by other guards as well is to keep the generic helper private and write concrete non-generic public extension methods. I think while this means writing a little more code it provides an opportunity to vary the behavior if needed in the specific extension instead of adding conditional logic to the generic method.

So, I think I’ll keep the generic method private but will take PRs for whatever concrete types are needed.
